policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      gpg:
        required: true
      spellcheck:
        locale: US
      maximumOfOneCommit: true
      conventional:
        types:
          - feat
          - fix
          - build
          - chore
          - ci
          - docs
          - pref
          - refactor
          - style
          - test
        descriptionLength: 72
