---
name: CI

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/ci.yml
      - flake.lock
      - flake.nix
      - 'flake-module/**'
      - 'template/**'
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci.yml
      - flake.lock
      - flake.nix
      - 'flake-module/**'
      - 'template/**'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          diagnostic-endpoint: ''

      - name: Check
        run: nix flake check

  check-template:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - template: root
          - template: root-project
          - template: subflake-project
            dev_path: dev
    name: check-template (${{ matrix.template }})

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
        with:
          diagnostic-endpoint: ''

      - name: Initialize project
        working-directory: ${{ runner.temp }}
        run: |
          mkdir -p project
          cd project
          git init

      - name: Initialize flake template
        working-directory: ${{ runner.temp }}/project
        run: |
          nix flake init -t ${{ github.workspace }}#${{ matrix.template }}
          git add --all --intent-to-add
          nix flake lock

      - name: Override dev-flake
        working-directory: ${{ runner.temp }}/project/${{ matrix.dev_path }}
        run: |
          nix flake lock --override-input dev-flake path:${{ github.workspace }}

      - name: Check
        working-directory: ${{ runner.temp }}/project
        run: |
          nix flake check --impure
